/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class AppTest {

    @Test
    public void testAppHasAGreeting() {
        assertEquals(4, 2 + 2);
    }
}
